### ISSUE TITLE
xmind文件能否更新一下

### ISSUE THREAD

**Issue by 0x0bit** [biaochenxuying/vue-family-mindmap#1]
可以将每个图片的xmind文件更新一下么？

**Comment by biaochenxuying** [comment]
> 可以将每个图片的xmind文件更新一下么？

图片都是从一个 xmind原文件 里面导出来的，xmind文件已经是最新的了。

**Comment by biaochenxuying** [comment]
> 可以将每个图片的xmind文件更新一下么？

我的天呐，我修改了 xmind 文件的展示形式后，居然没保存成功，吐血 。

我今晚再弄下，重新上传原文件吧。

**Comment by biaochenxuying** [comment]
已经修改正确，重新上传原文件了。

**Comment by savoygu** [comment]
大佬兄嘚，源文件好像没有上传成功啊，使用 [processon](https://www.processon.com/diagrams) 在线打不开（是支持 .xmind 格式的），没用 Xmind 软件试过是否能打开！
